name: CI
on:
  push:
    branches:
      - main
      - 'mf/**'
    paths:
      - "src/**"
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - run: npm config set '@krzysztoflen:registry' https://node.bit.dev
      - run: npm install
      - run: npm run build