name: CI
on:
  push:
    branches:
      - main
      - 'mf/**'
    paths:
      - "packages/applications/**"
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
